// import * as config from "config";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

config.autoAddCss = false; // Tell Font Awesome to skip adding the CSS automatically since it's being imported above.

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ticketing app by devWiz",
  description: "Generated by devWiz team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-page`}>
        <div>
          <Nav />
          <div className="text-default-text" >{children}</div>
        </div>
      </body>
    </html>
  );
}
